apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.global.app.name }}-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.global.app.name }}
  type: LoadBalancer
status:
  loadBalancer: {}
